name: Build ASP.NET project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước kiểm tra mã nguồn từ repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Cài đặt môi trường .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # Khôi phục dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Xây dựng dự án
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # Publish dự án
      - name: Publish the project
        run: dotnet publish -c Release -o ./publish
