name: Deploy ASP.NET to MonsterASP

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to MonsterASP via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}     # Thay thế đúng trường
          username: ${{ secrets.FTP_USERNAME }}  # Thay thế đúng trường
          password: ${{ secrets.FTP_PASSWORD }}  # Thay thế đúng trường
          local-dir: ./publish/
          server-dir: ${{ secrets.FTP_PATH }}   # Thay thế đúng trường
          protocol: sftp   # Có thể điều chỉnh nếu bạn dùng sftp hoặc ftps
