name: Deploy ASP.NET to MonsterASP

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to MonsterASP via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: ${{ secrets.FTP_PATH }}/   # Đảm bảo rằng đường dẫn này chính xác và kết thúc bằng dấu /
          protocol: ftps
          security: strict  # Chế độ bảo mật kết nối
          log-level: verbose  # Log chi tiết để kiểm tra lỗi
