name: Deploy ASP.NET to MonsterASP

on:
  push:
    branches:
      - master  # Chạy khi có thay đổi ở nhánh master
  pull_request:
    branches:
      - master  # Chạy khi có pull request tới nhánh master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to MonsterASP via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}  # Sử dụng secret FTP_HOST
          ftp-username: ${{ secrets.FTP_USERNAME }}  # Sử dụng secret FTP_USERNAME
          ftp-password: ${{ secrets.FTP_PASSWORD }}  # Sử dụng secret FTP_PASSWORD
          local-dir: ./publish  # Đường dẫn thư mục được publish
          server-dir: ${{ secrets.FTP_PATH }}  # Đường dẫn trên máy chủ
